# Generated by Django 3.0.8 on 2020-09-21 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('registration_number', models.CharField(max_length=200, unique=True, verbose_name='ID')),
                ('Enterprise', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('department', models.CharField(blank=True, max_length=300, verbose_name='Departamento')),
                ('job_name', models.CharField(blank=True, max_length=300, verbose_name='Cargo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='students/bulkupload/')),
            ],
        ),
    ]
