# Generated by Django 3.0.8 on 2020-10-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20201020_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_status',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, null=True),
        ),
    ]
