# Generated by Django 3.0.8 on 2020-12-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20201020_1152'),
        ('exams_db', '0004_auto_20201020_1247'),
        ('result', '0001_initial'),
        ('employees', '0003_student_current_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Employee',
        ),
    ]
