# Generated by Django 3.0.8 on 2020-09-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200921_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['payment_day']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_amount',
        ),
    ]
