# Generated by Django 3.0.8 on 2020-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200921_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_link',
            field=models.FileField(blank=True, upload_to='finance/receipts/'),
        ),
    ]
