# Generated by Django 3.0.8 on 2020-10-20 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20201020_1152'),
        ('employees', '0002_auto_20201020_1152'),
        ('finance', '0005_receipt_receipt_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='enterprise',
            field=models.CharField(blank=True, max_length=300, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Pago'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_link',
            field=models.FileField(blank=True, upload_to='finance/payments/', verbose_name='Link Pago'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider',
            field=models.CharField(blank=True, max_length=300, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Invoice', verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_paid',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha FV'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Student', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='exams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Exams', verbose_name='Exámenes'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Invoice', verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_link',
            field=models.FileField(blank=True, upload_to='finance/receipts/', verbose_name='Link'),
        ),
    ]
