# Generated by Django 3.0.8 on 2020-10-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='apply',
            field=models.CharField(max_length=800, verbose_name='Aplican'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='exams',
            field=models.CharField(max_length=800, verbose_name='Exámenes'),
        ),
    ]
