# Generated by Django 3.0.8 on 2020-10-20 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_auto_20201020_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('enterprise', models.CharField(blank=True, max_length=300, verbose_name='Empresa')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Student', verbose_name='Colaborador')),
            ],
            options={
                'ordering': ['employee'],
            },
        ),
        migrations.CreateModel(
            name='Exams_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Examen')),
                ('type_exam', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Periódico', 'Periódico'), ('Egreso', 'Egreso'), ('Post-Incapacidad', 'Post-Incapacidad')], max_length=300, verbose_name='Tipo Examen')),
                ('concept', models.CharField(choices=[('Apto', 'Apto'), ('Apto con Recomendaciones', 'Apto con Recomendaciones'), ('Apto con Restricciones', 'Apto con Restricciones'), ('Aplazado', 'Aplazado'), ('No Apto', 'No Apto'), ('Satisfactorio', 'Satisfactorio'), ('Satisfactorio con Recomendaciones', 'Satisfactorio con Recomendaciones'), ('No Satisfactorio', 'No Satisfactorio'), ('Sin Hallazgos Clínicos', 'Sin Hallazgos Clínicos'), ('Con Hallazgos Clínicos', 'Con Hallazgos Clínicos')], max_length=300, verbose_name='Concepto')),
                ('epp', models.CharField(max_length=400, verbose_name='EPP')),
                ('sve', models.CharField(choices=[('Ruido', 'Ruido'), ('Vibración', 'Vibración'), ('Presiones barométricas (altas o bajas)', 'Presiones barométricas (altas o bajas)'), ('Temperaturas extremas (altas o bajas)', 'Temperaturas extremas (altas o bajas)'), ('Radiaciones Ionizantes', 'Radiaciones Ionizantes'), ('Radiaciones no Ionizantes', 'Radiaciones no Ionizantes'), ('Iluminación', 'Iluminación'), ('Quimicos', 'Quimicos'), ('Biológicos', 'Biológicos'), ('Psicolaborales', 'Psicolaborales'), ('Ergonómicos', 'Ergonómicos'), ('Cardiovascular - Metabólico', 'Cardiovascular - Metabólico'), ('Ninguno', 'Ninguno')], max_length=300, verbose_name='SVE')),
                ('recomendations', models.CharField(max_length=1000, verbose_name='Recomendaciones')),
                ('recomendations_plan', models.CharField(max_length=800, verbose_name='Recomendaciones - Plan de Manejo')),
                ('restrictions', models.CharField(max_length=1000, verbose_name='Restriciones')),
                ('relocate', models.BooleanField(verbose_name='Reubicar')),
                ('comments', models.CharField(blank=True, max_length=200, verbose_name='Comentarios')),
                ('emp_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_db.Employee_Record', verbose_name='Colaborador')),
            ],
        ),
    ]
