# Generated by Django 3.0.8 on 2020-10-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams_record',
            old_name='emp_record',
            new_name='employee_record',
        ),
    ]
